sudo: required
services:
  - docker

before_install:
  - docker build -t igornovitsky/react-test -f ./client/Dockerfile.dev ./client
  # - docker build some other images for more tests

script:
  - docker run igornovitsky/react-test npm run test -- --coverage --watchAll=false

after_success:
  - docker build -t igornovitsky/multi-client ./client
  - docker build -t igornovitsky/multi-nginx ./nginx
  - docker build -t igornovitsky/multi-server ./server
  - docker build -t igornovitsky/multi-worker ./worker
  # Log in to the docker CLI
  # echo comand retrieves variable and passes it into stdin of the next command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push igornovitsky/multi-client
  - docker push igornovitsky/multi-nginx
  - docker push igornovitsky/multi-server
  - docker push igornovitsky/multi-worker